language: python
python:
- "3.5"
script:
  - pytest test_rpn.py
install:
  - pip install codecov
  - pip install colored --upgrade

script:
  - coverage run -m unittest rpn test_rpn

after_success:
  - codecov
